import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Box, 
  Typography, 
  Container, 
  Grid, 
  Card, 
  CardContent, 
  CardMedia, 
  TextField,
  InputAdornment,
  Chip,
  Divider,
  Button,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Paper,
  Tab,
  Tabs
} from '@mui/material';
import SchoolIcon from '@mui/icons-material/School';
import SearchIcon from '@mui/icons-material/Search';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import WarningIcon from '@mui/icons-material/Warning';
import AutorenewIcon from '@mui/icons-material/Autorenew';
import HomeWorkIcon from '@mui/icons-material/HomeWork';

/**
 * KnowledgeBase page - Displays educational resources for investment concepts
 * This supports the educational aspect mentioned in the UI design document
 */
const KnowledgeBase = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [activeTab, setActiveTab] = useState(0);
  const navigate = useNavigate();
  
  // Sample knowledge base categories
  const categories = [
    { id: 'basics', name: 'Investment Basics', count: 12 },
    { id: 'financial', name: 'Financial Concepts', count: 8 },
    { id: 'property', name: 'Property Evaluation', count: 15 },
    { id: 'tax', name: 'Tax Strategies', count: 7 },
    { id: 'risk', name: 'Risk Management', count: 9 },
    { id: 'financing', name: 'Financing Options', count: 11 }
  ];
  
  // Sample featured articles
  const featuredArticles = [
    {
      id: 1,
      title: 'Understanding Cap Rate: A Beginner\'s Guide',
      description: 'Learn how to calculate and interpret capitalization rate to evaluate investment properties.',
      image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=1050&q=80',
      category: 'Investment Basics',
      readTime: '5 min read'
    },
    {
      id: 2,
      title: 'Cash on Cash Return: Why It Matters',
      description: 'Explore how Cash on Cash Return helps measure the performance of income-producing properties.',
      image: 'https://images.unsplash.com/photo-1565514020179-026b92b4a420?ixlib=rb-4.0.3&auto=format&fit=crop&w=1050&q=80',
      category: 'Financial Concepts',
      readTime: '7 min read'
    },
    {
      id: 3,
      title: 'Property Inspection Checklist for Investors',
      description: 'A comprehensive checklist to evaluate property condition and identify potential issues before investing.',
      image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?ixlib=rb-4.0.3&auto=format&fit=crop&w=1050&q=80',
      category: 'Property Evaluation',
      readTime: '10 min read'
    }
  ];
  
  // Sample glossary terms
  const glossaryTerms = [
    {
      term: 'Cap Rate',
      definition: 'Capitalization rate is the rate of return on a real estate investment property based on the income that the property is expected to generate. It is calculated by dividing the property\'s net operating income by its current market value or acquisition cost.'
    },
    {
      term: 'Cash on Cash Return',
      definition: 'A rate of return that calculates the cash income earned on the cash invested in a property. It is calculated by dividing the annual pre-tax cash flow by the total amount of cash invested, expressed as a percentage.'
    },
    {
      term: 'Debt Service Coverage Ratio (DSCR)',
      definition: 'A measure of a property\'s cash flow available to pay debt obligations. It is calculated by dividing the property\'s net operating income by its total debt service, with higher ratios indicating better ability to cover debt payments.'
    },
    {
      term: 'Net Operating Income (NOI)',
      definition: 'The income generated by a property after deducting operating expenses but before accounting for taxes, financing costs, and non-cash expenses like depreciation.'
    },
    {
      term: 'Internal Rate of Return (IRR)',
      definition: 'A metric used to estimate the profitability of potential investments that takes into account the time value of money. It is the discount rate that makes the net present value of all cash flows equal to zero.'
    }
  ];
  
  // Handle tab change
  const handleTabChange = (event, newValue) => {
    setActiveTab(newValue);
  };
  
  // Filter glossary terms based on search
  const filteredTerms = glossaryTerms.filter(term => 
    term.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
    term.definition.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <Container maxWidth="xl" sx={{ py: 3 }}>
      {/* Header */}
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" fontWeight="bold" gutterBottom>
          Knowledge Base
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Enhance your investment knowledge with our educational resources and guides.
        </Typography>
      </Box>
      
      {/* Top Search and Browse Section */}
      <Paper 
        elevation={0} 
        sx={{ 
          p: 3, 
          borderRadius: 2, 
          mb: 4,
          background: 'linear-gradient(45deg, rgba(59,130,246,0.05) 0%, rgba(16,185,129,0.05) 100%)',
          border: '1px solid rgba(59,130,246,0.1)'
        }}
      >
        <Grid container spacing={3} alignItems="center">
          <Grid item xs={12} md={6}>
            <Typography variant="h5" fontWeight="bold" gutterBottom>
              Find Answers to Your Investment Questions
            </Typography>
            <Typography variant="body1" paragraph>
              Search our knowledge base for information on investment strategies,
              financial concepts, and property evaluation techniques.
            </Typography>
            <TextField
              fullWidth
              placeholder="Search for investment concepts, terms, or strategies..."
              variant="outlined"
              size="medium"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              InputProps={{
                startAdornment: (
                  <InputAdornment position="start">
                    <SearchIcon />
                  </InputAdornment>
                ),
              }}
              sx={{ 
                mb: 2,
                '& .MuiOutlinedInput-root': {
                  borderRadius: '8px',
                }
              }}
            />
            
            <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
              {categories.map(category => (
                <Chip 
                  key={category.id}
                  label={`${category.name} (${category.count})`}
                  clickable
                  color="primary"
                  variant="outlined"
                  onClick={() => console.log(`Clicked: ${category.name}`)}
                />
              ))}
            </Box>
          </Grid>
          
          <Grid item xs={12} md={6}>
            <Box sx={{ display: 'flex', justifyContent: 'center' }}>
              <img 
                src="https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&auto=format&fit=crop&w=1050&q=80" 
                alt="Investment Knowledge"
                style={{ 
                  maxWidth: '100%', 
                  height: 'auto',
                  maxHeight: '250px',
                  borderRadius: '8px',
                  boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)'
                }}
              />
            </Box>
          </Grid>
        </Grid>
      </Paper>
      
      {/* Tabs Navigation */}
      <Box sx={{ borderBottom: 1, borderColor: 'divider', mb: 3 }}>
        <Tabs 
          value={activeTab} 
          onChange={handleTabChange}
          sx={{ 
            '& .MuiTab-root': { 
              textTransform: 'none',
              fontWeight: 500,
              minWidth: 100,
            },
          }}
        >
          <Tab label="Featured Articles" />
          <Tab label="Investment Guides" />
          <Tab label="Glossary" />
          <Tab label="Video Tutorials" />
        </Tabs>
      </Box>
      
      {/* Tab Content */}
      <Box sx={{ mb: 4 }}>
        {/* Featured Articles Tab */}
        {activeTab === 0 && (
          <Grid container spacing={3}>
            {featuredArticles.map(article => (
              <Grid item xs={12} md={4} key={article.id}>
                <Card sx={{ 
                  height: '100%', 
                  display: 'flex', 
                  flexDirection: 'column',
                  borderRadius: 2,
                  transition: 'transform 0.3s ease',
                  '&:hover': {
                    transform: 'translateY(-8px)',
                    boxShadow: 3
                  }
                }}>
                  <CardMedia
                    component="img"
                    height="200"
                    image={article.image}
                    alt={article.title}
                  />
                  <CardContent sx={{ flexGrow: 1 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
                      <Chip 
                        label={article.category} 
                        size="small" 
                        color="primary" 
                        sx={{ height: '24px' }}
                      />
                      <Typography variant="caption" color="text.secondary">
                        {article.readTime}
                      </Typography>
                    </Box>
                    <Typography variant="h6" component="h2" fontWeight="bold" gutterBottom>
                      {article.title}
                    </Typography>
                    <Typography variant="body2" color="text.secondary" paragraph>
                      {article.description}
                    </Typography>
                    <Button 
                      endIcon={<ArrowForwardIcon />} 
                      size="small"
                      sx={{ p: 0, minWidth: 'auto' }}
                    >
                      Read More
                    </Button>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>
        )}
        
        {/* Investment Guides Tab */}
        {activeTab === 1 && (
          <Grid container spacing={3}>
            <Grid item xs={12} md={4}>
              <Paper sx={{ p: 3, borderRadius: 2, height: '100%' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                  <HomeWorkIcon color="primary" sx={{ fontSize: 32, mr: 2 }} />
                  <Typography variant="h6" fontWeight="bold">
                    Beginner's Guide to Property Investment
                  </Typography>
                </Box>
                <Typography variant="body2" paragraph>
                  A comprehensive guide to getting started with property investment, 
                  covering key concepts, market analysis, and financing options.
                </Typography>
                <List dense>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Understanding market cycles" />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Property valuation methods" />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Risk assessment fundamentals" />
                  </ListItem>
                </List>
                <Button 
                  endIcon={<ArrowForwardIcon />} 
                  sx={{ mt: 2 }}
                  color="primary"
                  variant="outlined"
                >
                  Read Guide
                </Button>
              </Paper>
            </Grid>
            
            <Grid item xs={12} md={4}>
              <Paper sx={{ p: 3, borderRadius: 2, height: '100%' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                  <WarningIcon color="warning" sx={{ fontSize: 32, mr: 2 }} />
                  <Typography variant="h6" fontWeight="bold">
                    Investment Risk Management
                  </Typography>
                </Box>
                <Typography variant="body2" paragraph>
                  Learn how to identify, assess, and mitigate various risks associated 
                  with property investment to protect your portfolio.
                </Typography>
                <List dense>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Market volatility risks" />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Property-specific risks" />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Financial risk management" />
                  </ListItem>
                </List>
                <Button 
                  endIcon={<ArrowForwardIcon />} 
                  sx={{ mt: 2 }}
                  color="primary"
                  variant="outlined"
                >
                  Read Guide
                </Button>
              </Paper>
            </Grid>
            
            <Grid item xs={12} md={4}>
              <Paper sx={{ p: 3, borderRadius: 2, height: '100%' }}>
                <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
                  <AutorenewIcon color="info" sx={{ fontSize: 32, mr: 2 }} />
                  <Typography variant="h6" fontWeight="bold">
                    ROI Optimization Strategies
                  </Typography>
                </Box>
                <Typography variant="body2" paragraph>
                  Advanced techniques to maximize your return on investment through 
                  strategic decision-making and portfolio optimization.
                </Typography>
                <List dense>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Value-add investment strategies" />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Cash flow enhancement techniques" />
                  </ListItem>
                  <ListItem>
                    <ListItemIcon sx={{ minWidth: 32 }}>
                      <CheckCircleIcon color="success" fontSize="small" />
                    </ListItemIcon>
                    <ListItemText primary="Tax optimization approaches" />
                  </ListItem>
                </List>
                <Button 
                  endIcon={<ArrowForwardIcon />} 
                  sx={{ mt: 2 }}
                  color="primary"
                  variant="outlined"
                >
                  Read Guide
                </Button>
              </Paper>
            </Grid>
          </Grid>
        )}
        
        {/* Glossary Tab */}
        {activeTab === 2 && (
          <Box>
            <Box sx={{ mb: 3 }}>
              <TextField
                fullWidth
                placeholder="Search glossary terms..."
                variant="outlined"
                size="small"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                InputProps={{
                  startAdornment: (
                    <InputAdornment position="start">
                      <SearchIcon />
                    </InputAdornment>
                  ),
                }}
              />
            </Box>
            
            <Paper sx={{ p: 3, borderRadius: 2 }}>
              {filteredTerms.length > 0 ? (
                filteredTerms.map((item, index) => (
                  <Box key={item.term}>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="h6" fontWeight="bold" gutterBottom>
                        {item.term}
                      </Typography>
                      <Typography variant="body2">
                        {item.definition}
                      </Typography>
                    </Box>
                    {index < filteredTerms.length - 1 && <Divider sx={{ my: 2 }} />}
                  </Box>
                ))
              ) : (
                <Typography>No glossary terms match your search.</Typography>
              )}
            </Paper>
          </Box>
        )}
        
        {/* Video Tutorials Tab */}
        {activeTab === 3 && (
          <Box sx={{ textAlign: 'center', py: 4 }}>
            <SchoolIcon sx={{ fontSize: 48, color: 'primary.main', mb: 2 }} />
            <Typography variant="h6" gutterBottom>
              Video Tutorial Library
            </Typography>
            <Typography variant="body1">
              Our video tutorial library is coming soon. Check back for educational videos 
              on property investment, financial analysis, and market trends.
            </Typography>
          </Box>
        )}
      </Box>
      
      {/* Ask the Expert Section */}
      <Paper 
        elevation={0} 
        sx={{ 
          p: 3, 
          borderRadius: 2,
          border: '1px solid',
          borderColor: 'divider',
          display: 'flex',
          flexDirection: { xs: 'column', md: 'row' },
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 3
        }}
      >
        <Box>
          <Typography variant="h5" fontWeight="bold" gutterBottom>
            Didn't find what you're looking for?
          </Typography>
          <Typography variant="body1">
            Ask our AI assistant for help with any investment questions you have.
            Get personalized guidance based on your specific situation.
          </Typography>
        </Box>
        
        <Button 
          variant="contained" 
          size="large"
          onClick={() => navigate('/')}
          sx={{ minWidth: '200px' }}
        >
          Chat with AI Assistant
        </Button>
      </Paper>
    </Container>
  );
};

export default KnowledgeBase;